### ISSUE TITLE
User management questions

### ISSUE THREAD

**Issue by Mte90** [unfoldadmin/django-unfold#905] opened 2024-12-17 17:52 UTC
I am using the latest unfold version but I have a couple of question that I wasn't able to resolve reading the doc and the source code.

* How I can enable the recovery password for this admin dashboard for the users? Ref https://github.com/unfoldadmin/django-unfold/issues/590
* How I can customize the user creation form to add the email field as example?

**Comment by lukasvinclav** [comment] 2024-12-17 18:02
1. I think you already answered your first question in the original issue. It requires manual implementation which is out the scope Unfold. In the same issue, I'm pointing it is a duplicate of #384 where I'm providing detailed explanation.
2. For changing the form in Django admin you can configure `add_form` property in `ModelAdmin` to point at the custom form.

**Comment by Mte90** [comment] 2024-12-17 18:04
Thanks for the reply I will check that but basically both require custom implementations.

**Closed** 2024-12-18 07:45 UTC
