### ISSUE TITLE
MPTTModelAdmin does not work with ModelAdmin

### ISSUE THREAD

**Issue by YordanPetrovDS** [unfoldadmin/django-unfold#713] opened 2024-09-02 14:54 UTC
MPTT admin does not compatible with django-unfold. Could you please help me to fix this?
code:
```
from mptt.admin import MPTTModelAdmin
from unfold.admin import ModelAdmin, TabularInline
@admin.register(ProductCategory)
class ProductCategoryAdmin(MPTTModelAdmin, ModelAdmin):
    list_display = ("title", "parent", "display_attributes", "display_tax_groups")
    search_fields = ("title",)
    mptt_level_indent = 20
    list_filter = ("parent",)
    inlines = [ProductCategoryAttributesInline, ProductCategoryTaxGroupsInline]
```

result:
![image](https://github.com/user-attachments/assets/ffd05e2f-6e31-46bc-9a1a-c308c740f172)

**Comment by lukasvinclav** [comment] 2024-09-03 04:42
Hi, this is duplicate of #366 so I'm closing this ticket.

**Closed by lukasvinclav** 2024-09-03 04:42 UTC
