### ISSUE TITLE
More control over Inlines placement

### ISSUE THREAD

**Issue by zhurbey** [unfoldadmin/django-unfold#428] opened 2024-05-31 11:30 UTC
Right now the only option available is to place all inlines in the first tab and after all other fields. It would be great to have more control over that.

1. Minimal: place Inline into a separate tab, Juzzmin is able of doing exactly that
2. Better: group inlines together, configure to put multiple inlines in one tab instead of putting each into a separate one
3. Perfect: threat inline block just like any other field, complete control over its placement - define in which tab and after and before which fields to put it exactly. Perfect configuration would look the following:

```python
fieldsets = [
    (
        "General",
        {
            "classes": ["tab"],
            "fields": [
                "prop1",
                "inline block 1",
                "prop2",
            ],
        }
    ),
    (
        "Second Section",
        {
            "classes": ["tab"],
            "fields": [...],
        },
    ),
]
```

**Comment by lukasvinclav** [comment] 2024-06-01 05:59
Duplicate of #295

**Closed by lukasvinclav** 2024-06-01 05:59 UTC
