### ISSUE TITLE
Can SideBar add display control for models in Multi-Standalone UnfoldAdminSite?

### ISSUE THREAD

**Issue by Huanghibo** [unfoldadmin/django-unfold#754] opened 2024-09-19 04:11 UTC
Settings->> UNFOLD sidebar and tab configured models are displayed on all Sites.
**Do you have any examples?**
Yes.
For example: link or screenshot
![1](https://github.com/user-attachments/assets/9fa6195a-51d1-42f1-8a5d-923d0e1a323c)
![2](https://github.com/user-attachments/assets/8e68343e-03ed-4834-befa-c04aaf4bd241)

**Is it a third party application feature request?**
No.
For example: Yes or No

**In case of third party application, when it was updated last time?**
No.
For example: last week

**Describe your feature request**

Describe the feature in detail. Feel free to link existing pull request, implemeting a new feature.

**Comment by justinqian42** [comment] 2024-09-20 00:23
Hi @Huanghibo ,

Noticed that you're also using django-allauth. Just wondering if you're using it for the admin site authentication (with unfold)? If so, how did you apply it?
I followed the guide here https://docs.allauth.org/en/latest/common/admin.html but it didn't work.

Thanks in advance.
Justin

**Comment by lukasvinclav** [comment] 2024-09-20 10:12
@justinqian42 please create a separate ticket related to django-allauth and I will take a look.

**Comment by lukasvinclav** [comment] 2024-09-20 10:17
To be honest, I don't understand the issue. I think without the example repository where I can reproduce the issue, I would be not able to help you.

I'm going to close the issue right now because it is not containing all information which issue template is requesting. Feel free to create new issue with all details and I will be happy to help you.

**Closed by lukasvinclav** 2024-09-20 10:17 UTC

**Comment by justinqian42** [comment] 2024-09-22 23:33
> @justinqian42 please create a separate ticket related to django-allauth and I will take a look.

Thanks mate. @Huanghibo has raised #759.

**Comment by justinqian42** [comment] 2024-09-23 00:07
> To be honest, I don't understand the issue. I think without the example repository where I can reproduce the issue, I would be not able to help you.
> 
> I'm going to close the issue right now because it is not containing all information which issue template is requesting. Feel free to create new issue with all details and I will be happy to help you.

I've provided @Huanghibo a workaround with https://github.com/unfoldadmin/django-unfold/issues/759#issuecomment-2367029003
