### ISSUE TITLE
Seems like StackedInline is broken if no records found

### ISSUE THREAD

**Issue by skazancev** [unfoldadmin/django-unfold#753] opened 2024-09-18 14:26 UTC
**What version of Unfold are you using?**

Version: 0.38.0

**What version of Django are you using?**

For example: 5.1.1

**What browser are you using?**

For example: Doesn't matter

**Did you checked changelog/commit history, if the bug is not already fixed?**
Bug is in [this](https://github.com/unfoldadmin/django-unfold/commit/cb39ca37ebeff0c1379ea1ac020091f2dc4fd324) commit

**Are you able to replicate the bug in the demo site?**
<img width="1176" alt="image" src="https://github.com/user-attachments/assets/7fd8b62d-b2a8-4b57-9f18-6c366cd6b252">

No add another record button, there is should be an additional condition `if not inline_admin_formset.has_add_permission` on line 16 in stacked.html (like in `tabular.html`)

So the final code on line 16 is: `{% if not inline_admin_formset.has_add_permission and inline_admin_formset.forms|length == 0 %}`

**Comment by lukasvinclav** [comment] 2024-09-20 10:21
Yes, you are right. This is duplicate of #735. I will take a look on that.

**Closed by lukasvinclav** 2024-09-20 10:21 UTC

**Comment by lukasvinclav** [comment] 2024-09-20 14:35
Thanks. Fixed in https://github.com/unfoldadmin/django-unfold/pull/758

**Comment by skazancev** [comment] 2024-09-20 15:08
Good job, thank you!

**Comment by lukasvinclav** [comment] 2024-09-20 15:08
Did you tested it?
