### ISSUE TITLE
navigation group item removed for all users

### ISSUE THREAD

**Issue by summerthe** [unfoldadmin/django-unfold#281] opened 2024-02-05 13:32 UTC
`navigation` item permission modifies the global navigation setting for all users. 

To reproduce the issue, follow these steps:

1. The navigation consists of 5 items, with the last item having a permission setting that allows access only to superusers.
```py
"SIDEBAR": {
  "navigation": [
    {
      "items": [
        {...},
        {...},
        {...},
        {...},
        {
          ...
          "permission": lambda request: request.user.is_superuser,
        }
      ]
    }
  ]
}
```

2. Access the /admin/ with two different users: one as a superuser and the other as a staff member.

3. When logged in as the superuser, the fifth item will be visible. However, when logged in as a staff member, the fifth item won't be displayed.

4. Switch back to the superuser account, and observe that the fifth item is now missing. This is because the code is updating the global setting for all users. The suggested solution is to use deepcopy for the `navigation` list.

[Code link](https://github.com/unfoldadmin/django-unfold/blob/a2700bf0f42ae2a78fd46c6376383884b7f141a2/src/unfold/sites.py#L274).

**Comment by lukasvinclav** [comment] 2024-02-05 16:10
@summerthe are you using version 0.20.3?

**Comment by summerthe** [comment] 2024-02-08 17:50
@lukasvinclav this

django==5.0.1
django-environ==0.11.2
django-import-export==3.3.6
django-unfold==0.20.1

**Comment by summerthe** [comment] 2024-02-08 18:07
upgraded to django-unfold==0.20.3 and issue is gone. Thanks.

**Comment by Biftor** [comment] 2024-02-08 23:54
Hi, I am facing the same problem
django-unfold==0.20.3
just seeing sections title

`        super_admin_list = [
            {
                "separator": True,
                "title": _("Users Section"),
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:accounts_account_changelist"),
                        "badge": "23",
                        "permission": HasAnyAppPermission(request=request, app_name="accounts",
                                                          model_name="account")(),
                    },
                    {
                        "title": _("Users Profiles"),
                        "icon": "user_attributes",
                        "link": reverse_lazy("admin:profiles_userprofile_changelist"),
                        "permission": HasAnyAppPermission(request=request, app_name="profiles",
                                                          model_name="userprofile")(),
                    },
                    .
                    .
                    ]
                    }
                    
                    `

**Comment by summerthe** [comment] 2024-02-12 21:04
@lukasvinclav 
The same issue is occuring for badge as well; 

I have one badge callback that returns different data based on type of user. 

```py
def callback(...):
  if request.user.is_superuser:
     return "superuser_specific_data"
  return "staff_data"
```
Steps of reproducing this issue:
- Login with superuser user you will see `superuser_specific_data` in badge 
- In another window login with staff user, you will again see `superuser_specific_data` again but it should return `staff_data`.

Dunno where this caching is happening.

In above case try login with staff first and then login with superuser. The first result is cached and being return to all users.

**Comment by lukasvinclav** [comment] 2024-02-16 14:35
@summerthe I'm closing the issue because the original problem with permission has been fixed. You can open a new issue but please provide a repository where it is possible to reproduce the problem.

**Closed by lukasvinclav** 2024-02-16 14:35 UTC
